### ISSUE TITLE
ruby for it…

### ISSUE THREAD

**Issue by barmic** [yazgoo/kyrbeis#1]
Hello

I see your post on linuxfr and I find that usage of ruby and gemfile is very bolerplat for make only few lines of shell script :

```sh
#!/bin/bash

shopt -s glostar

cd "${HOME}/dotfiles"

for dotfile in ( **/* ) do
    test -f "${dotfile}" || continue
    destination="${HOME}/${dotfile//__/.}"
    if [[ -f "${destination}" ]]; then
        echo "  ${destination} already exist"
    else
        mkdir -p "${destination%/*}"
        ln -s "${dotfile}" "${destination}"
        echo "→ ${destination} already exist"
    fi
done
```

It's not tested but if you think that can be useful for you :)

Thank you for the share!

**Comment by yazgoo** [comment]
Thanks, this is awesome !

gem configuration is rather simple so I don't think it is such a hassle :).
It gives many benefits (simple install, version handling), and ruby might allow to add complexity with more maintainability than shell.

Hence I'm closing this, but thanks for sharing !
